# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-FASTASequence-File
version:      0.02
version_from: lib/Bio/FASTASequence/File.pm
installdirs:  site
requires:
    Bio::FASTASequence:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
